FLASK_APP=app.py
FLASK_DEBUG=true 
FLASK_ENV=development

LANDSATXPLORE_USERNAME=pruebaeos123@
LANDSATXPLORE_PASSWORD=pruebaeos123#

CPLUS_INCLUDE_PATH=/usr/include/gdal
C_INCLUDE_PATH=/usr/include/gdal